### ISSUE TITLE
Add Bootstrap base theme

### ISSUE THREAD

**Issue by pdt256** [inklabs/kommerce-templates#1]
Later we can port this to a separate foundation base theme.

**Comment by pdt256** [comment]
I had to stomp on the foundation (-alt.twig) files in these commits:
6739774f67ffe46474e2f311ad8f98ebfef0a091
a9f66a3aacb9d1a6587347579236df13898dd151

The differences between foundation and bootstrap were hindering the template migration process from PHP to Twig.

**Comment by jasonraimondi** [comment]
You just keep adding the bootstrap pages and I'll worry about the foundation port
